package com.lksback.springboot.dto.exception;

/**
 * Created by Tree.Yip on 11/02/2020.
 */
public enum LksErrors {

    LKS_VERSION_MISMATCH(8000),
    LKS_ACCESS_IS_DENIED(8001),
    LKS_REQUEST_DATA_PARTIAL_EMPTY(8002),
    LKS_INTERNAL_SERVER_ERROR(8003),
    LKS_INPUT_INVALID(8004),
    LKS_K_ASSET_NOT_EXISTS(8005),
    LKS_K_ASSET_RETAIN_FAILURE_FILE_EMPTY(8006),
    LKS_K_ASSET_FETCH_FAILURE_FILE_UNAVAILABLE(8007),
    LKS_L_KEY_VALUE_PAIR_IS_EXISTS(8008),
    LKS_L_KEY_VALUE_PAIR_NOT_EXISTS(8009),
    LKS_L_KEY_VALUE_PAIR_NOT_ENABLE(8010),
    LKS_L_BRAND_IS_EXISTS(8011),
    LKS_L_BRAND_NOT_EXISTS(8012),
    LKS_L_CATEGORY_IS_EXISTS(8013),
    LKS_L_CATEGORY_NOT_EXISTS(8014),
    LKS_L_CITY_IS_EXISTS(8015),
    LKS_L_CITY_NOT_EXISTS(8016),
    LKS_L_ORDER_STATUS_IS_EXISTS(8017),
    LKS_L_ORDER_STATUS_NOT_EXISTS(8018),
    LKS_L_WAREHOUSE_IS_EXISTS(8019),
    LKS_L_WAREHOUSE_NOT_EXISTS(8020),
    LKS_K_CUSTOMER_IS_EXISTS(8021),
    LKS_K_CUSTOMER_NOT_EXISTS(8022),
    LKS_K_CUSTOMER_ADDR_IS_EXISTS(8023),
    LKS_K_CUSTOMER_ADDR_NOT_EXISTS(8024),
    LKS_K_EXPENSE_IS_EXISTS(8025),
    LKS_K_EXPENSE_NOT_EXISTS(8026),
    LKS_K_ORDER_IS_EXISTS(8027),
    LKS_K_ORDER_NOT_EXISTS(8028),
    LKS_K_INVOICE_IS_EXISTS(8029),
    LKS_K_INVOICE_NOT_EXISTS(8030),
    LKS_K_INVOICE_NOT_MODIFIABLE(8031),
    LKS_K_ORDER_PRODUCT_IS_EXISTS(8032),
    LKS_K_ORDER_PRODUCT_NOT_EXISTS(8033),
    LKS_K_ORDER_PRODUCT_OVER_ALLOCATE(8034),
    LKS_K_ORDER_PRODUCT_PURCHASE_IS_EXISTS(8035),
    LKS_K_ORDER_PRODUCT_PURCHASE_NOT_EXISTS(8036),
    LKS_K_PURCHASE_IS_EXISTS(8037),
    LKS_K_PURCHASE_NOT_EXISTS(8038),
    LKS_K_PURCHASE_EXCEEDS_ALLOCATE(8039),
    LKS_K_ADMIN_NOT_DROPABLE(8040),
    LKS_K_MEMBER_ALREADY_EXISTS(8041),
    LKS_K_MEMBER_NOT_EXISTS(8042),
    LKS_K_MEMBER_ALREADY_ACTIVATED(8043),
    LKS_K_MEMBER_NOT_ACTIVATED(8044),
    LKS_K_MEMBER_INVALID_EMAIL_ADDRESS(8045),
    LKS_K_MEMBER_GROUP_NOT_EXISTS(8046),
    LKS_T_SMS_EXCEPTION_PAYLOAD_LENGTH_EXCEED_LIMIT(8047),
    LKS_T_VERIFICATION_CODE_REQUEST_DENIED(8048),
    LKS_T_VERIFICATION_CODE_EXPIRY_OR_INVALID(8049),
    ;

    private Integer code;

    LksErrors(Integer code) {
        this.code = code;
    }

    public Integer getCode() {
        return code;
    }
}
